CREATE TABLE conta (
	idConta BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;